version: '2.1'

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset
orbs:
  path-filtering: circleci/path-filtering@0.1.2
  codecov: codecov/codecov@3.2.4

upload:
      description: |
          Upload your coverage reports to Codecov without dealing with complex
          configurations. This orb helps you get coverage results quickly so that you
          can breathe easier and commit your code with confidence.

          If running on `alpine` builds, the orb will need `coreutils`, `curl`, and
          `gnupg` in order to validate.
      parameters:
          file:
              default: ""
              description: Path to the code coverage data file to upload.
              type: string
          flags:
              default: ""
              description: Flag the upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
              type: string
          token:
              default: CODECOV_TOKEN
              description: Set the private repository token as the value of the variable CODECOV_TOKEN using CircleCI Environment Variables.
              type: env_var_name
          upload_name:
              default: ${CIRCLE_BUILD_NUM}
              description: Custom defined name of the upload. Visible in Codecov UI
              type: string
          validate:
              default: true
              description: Validate the uploader before uploading the codecov result.
              type: boolean
          version:
              default: latest
              description: Which version of the Codecov Uploader to use (defaults to 'latest')
              type: string
          when:
              default: always
              description: When should this step run?
              type: string
          xtra_args:
              default: ""
              description: Any extra flags as provided by the bash uploader (e.g. `-v -Z`).
              type: string

workflows:
  # the always-run workflow is always triggered, regardless of the pipeline parameters.
  always-run:
    jobs:
      # the path-filtering/filter job determines which pipeline
      # parameters to update.
      - path-filtering/filter:
          name: check-updated-files
          # 3-column, whitespace-delimited mapping. One mapping per
          # line:
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            .circle/.* lint_only false
            cmake/.* lint_only false
            configs/.* lint_only false
            csrc/.* lint_only false
            demo/csrc/.* lint_only false
            docker/.* lint_only false
            mmdeploy/.* lint_only false
            requirements/.* lint_only false
            tests/.* lint_only false
            third_party/.* lint_only false
            tools/.* lint_only false
          base-revision: master
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete. In this case, we are using the parent dynamic
          # configuration itself.
          config-path: .circleci/test.yml

  upload-to-codecov:
    jobs:
    - codecov/upload